name: CI Builds

permissions:
  contents: read

on:
  push:
    branches: [master, develop]
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        description: 'Branch to build'
        options: [master, develop]

concurrency: ci_build-${{ github.event.inputs.branch || github.ref_name }}

jobs:
  ci_builds:
    runs-on: ubuntu-latest

    name: "CI Build"
    timeout-minutes: 1380

    container: ghcr.io/qmk/qmk_cli

    steps:
    - name: Disable safe.directory check
      run : git config --global --add safe.directory '*'

    - uses: actions/checkout@v3
      with:
        submodules: recursive
        ref: ${{ github.event.inputs.branch || github.ref }}

    - name: Install dependencies
      run: pip3 install -r requirements.txt

    - name: Compile For Sophie
      run: qmk compile -e CONVERT_TO=liatris -kb splitkb/aurora/corne -km default

    - name: Compile For Paul
      run: qmk compile -e CONVERT_TO=liatris -kb splitkb/aurora/lily58 -km main

    - name: 'Upload artifacts'
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: artifacts-${{ github.event.inputs.branch || github.ref_name }}-${{ matrix.keymap }}
        if-no-files-found: ignore
        path: |
          *.uf2
